export { Main } from "./Main"
export { AuthPage } from "./AuthPage"
export { RatingPage } from "./RatingPage"
export { AccountPage } from "./AccountPage"
export { StatisticPage } from "./StatisticPage"
export { FAQPage } from "./FAQPage"
